version: "3.12"

services:
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django_web:
    build: .
    command: >
      sh -c "
      if [ ! -f /app/manage.py ]; then
        django-admin startproject app .
      fi;
      cd /app;
      if [ ! -d core ]; then
        python manage.py startapp core;
      fi;
      if [ ! -d inventory ]; then
        python manage.py startapp inventory;
      fi;
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db

volumes:
  postgres_data:
